services:
  - type: web
    name: sentiment-analyzer
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
      cd frontend && npm install && npm run build
      cd .. && cp -r frontend/out backend/frontend-build
    startCommand: cd backend && python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0